Task 2 1
s-SoMka-s/OOP pull request #11
Opened 2021-03-14 11:38 UTC by s-SoMka-s

2021-03-25 02:29 UTC, vlitomsk requested changes
немного переделать и ок

2021-03-25 02:29 UTC, vlitomsk commented on semester_2/task_2_1/src/main/java/task2_1/ShiftedIterator.java
> +        }
Это не будет работать с бесконечными последовательностями -- зависнет.

2021-04-14 05:16 UTC, s-SoMka-s commented on semester_2/task_2_1/src/main/java/task2_1/ShiftedIterator.java
> +        }
@vlitomsk Да, и не только это. Еще основной поиск непростого числа тоже будет бесконечно долго выполнятся. Даже если я тут что-то поменяю.
И разве может быть бесконечно большая последовательность во входном ArrayList-e???
+ по логике мне же вначале нужно итератор подготовить, а потом им пользоваться. А если попытаться избежать зависаний - готовить его прямо на лету в процессе подсчета, но тогда он тут в принципе не нужен. Можно дергать просто сразу каждый Nth-ный элемент с массива(что опять же зависнет на бесконечных последовательностях)

2021-04-14 16:37 UTC, s-SoMka-s commented on semester_2/task_2_1/src/main/java/task2_1/ShiftedIterator.java
> +        }
@vlitomsk Перепишу через блокирующую очередь тогда.

2021-04-21 06:32 UTC, vlitomsk commented on semester_2/task_2_1/src/main/java/task2_1/ShiftedIterator.java
> +        }
Бесконечно большую последовательность можно реализовать через Iterator, который на hasNext() всегда будет отвечать true.

2021-04-21 06:38 UTC, vlitomsk commented on semester_2/task_2_1/src/main/java/task2_1/ShiftedIterator.java
> +        }
Просто все входы можно переделать на Iterator-ы, так будет и более универсально.
В шарпах, например, есть IEnumerable для перечислимых коллекций с хорошей интеграцией в язык, такой, что можно не заморачиваться с реализацией интерфейсов. Всё входит и выходит. Джява в этом плане более консервативна =(

2021-04-21 13:19 UTC, s-SoMka-s commented on semester_2/task_2_1/src/main/java/task2_1/ShiftedIterator.java
> +        }
@vlitomsk ну да yield
в джаве то тоже есть такая тема, blockingCollection (ну или не blocking)
крч я понял что тут надо сделать часть producer & consumer только с допущением, что у нас изначально подготовлены данные(или нет в будущем). Ну и раз джава имеет в арсенале удобную очередь для таких задач - то почему бы ей не воспользоваться. Собственно это я и сделал.

2021-04-21 13:20 UTC, s-SoMka-s commented on semester_2/task_2_1/src/main/java/task2_1/ShiftedIterator.java
> +        }
я вообще выпилил итератор, и эту предварительную подготовку
просто набор потоков отправил развлекаться с разделяемой очередью данных

2021-04-22 03:42 UTC, merged