Task3_1 Gregorian Calendar
s-SoMka-s/OOP pull request #6
Opened 2020-11-28 05:11 UTC by s-SoMka-s

2020-12-04 03:48 UTC, vlitomsk approved these changes
ок принято

2020-12-04 03:48 UTC, vlitomsk commented on task3_1/src/main/java/task3_1/MyDate.java
> +    // TO-DO Implement
implement

2020-12-04 03:48 UTC, vlitomsk requested changes
req

2020-12-05 12:50 UTC, s-SoMka-s commented on task3_1/src/main/java/task3_1/MyDate.java
> +    // TO-DO Implement
- [ ] Implement

2020-12-11 05:13 UTC, vlitomsk approved these changes
ок принято

2021-02-21 08:25 UTC, merged