Task4_1 My calculator
s-SoMka-s/OOP pull request #9
Opened 2020-11-29 13:29 UTC by s-SoMka-s

2020-12-04 03:17 UTC, vlitomsk requested changes
req

2020-12-04 03:17 UTC, vlitomsk commented on task4_1/src/main/java/task4_1/MyCalculator.java
> +        var op1 = this.numbers.pop();
А если не хватит элементов в стеке?

2020-12-04 03:17 UTC, vlitomsk commented on task4_1/src/main/java/task4_1/MyCalculator.java
> +            case "+":
Вот и хороший учебный пример для выделения новых программных абстракций и изучения принципов SOLID подоспел.
Представим, что пользователю класса понадобилось расширить функциональность калькулятора -- добавить новые операции. Для него будет проще, если мы будем предоставлять эту возможность встраивания нового в явном виде, путем исполнения указания "добавь вот такую реализацию вот такой операции", по сравнению со сценарием, в котором пользователь разбирается во всем коде калькулятора и изменяет его код. Может, в примере про калькулятор это не так ясно, но в более сложных классах, которые разрабатывали разные авторы на протяжении нескольких лет, бывает трудно выхватить нужное место для изменений, если явный механизм расширения не предусмотрен. И получается, что в сказочном доме, где все электрические приборы кроме чайника описаны в плане строительства и вмурованы в стену, а розетки решили не ставить, придется искать проводку в стене, раздалбливать её перфоратором и подключать чайник на скрутку. И не факт, что после такого подключения электричество будет работать нормально.

Поэтому предлагаю вынести описания и реализацию конкретных операций и функций калькулятора за пределы самого калькулятора, для этого выделить интерфейс операции.

2020-12-04 03:17 UTC, vlitomsk commented on task4_1/src/main/java/task4_1/MyCalculator.java
> +        return 0d;
return 0?

2020-12-05 14:26 UTC, s-SoMka-s commented on task4_1/src/main/java/task4_1/MyCalculator.java
> +            case "+":
@vlitomsk кажется как-то так

2020-12-11 05:13 UTC, vlitomsk approved these changes
ок принято

2021-02-21 08:24 UTC, merged